### ISSUE TITLE
Integration with gpython? 

### ISSUE THREAD

**Issue by drew-512** [slongfield/pyfmt#15]
Hi @slongfield 

We are considering using pyfmt with [gpython](https://github.com/go-python/gpython) to add `.format` support.  Is this something you'd be interested in helping support or at least bless?  Your efforts and support would be welcome but the ask would be for you to consider merging any minor PRs to `pyfmt` that make good sense.    I think `pyfmt` is perfect for gpython!

Best,
Drew

**Comment by drew-512** [comment]
I'm seeing the license for `pyfmt` is BSD-3, so I will need help in understanding if this is compatible with `gpython`'s license.

**Comment by slongfield** [comment]
Hi @drew-512,

I wrote this as a hobby project a while ago, mostly to play with integration between Golang and Python's Hypothesis testing library. Uploaded and open-sourced in case it could ever be useful to someone.

Certainly willing to bless usage, but I haven't been actively using Golang in a few years, so there may be some things in here that aren't up to current best practices. I can help support to a small degree (e.g., review and merge minor PRs), and might be up for re-licensing (though it looks like gpython is also BSD-3).  

It is not an exact match to Python's format library, as you can see the in the fuzz testing exceptions (`test/hypothesis_test.py`). Other than a few added features (e.g., `{:t}` to support `fmt`s `%T`), there are also some small formatting differences that result from using the Golang `fmt` library under the hood. For example, `0f` is printed as  `0E+00` vs Python's `0.E+00`.  Could probably be fixed if you wanted an exact match, and the fuzz testing framework is there for finding any other mismatches.

Best,

--Stephen

**Comment by drew-512** [comment]
Hi Stephen, awesome.  We appreciate your support and blessing!

Does it work if you push a rev that brings things to 1.15, 1.16, or 1.17 and any other changes or notes that make sense to you before proceeding?   Otherwise, I'm happy to submit a PR down the road when I have a handle on things.  

You'll see from that other post I have a worklist of items before I get to this, so I anticipate a month or so til I get to this.

**Comment by slongfield** [comment]
Sure, done.  Cleaned up some small bit-rot (e.g., moving from the old free Travis to GitHub actions), and tested on more versions. Should work fine for 1.15.

Also fixed one of the long-standing mismatches that made the hypothesis testing a bit uglier, and ran a few hours worth of fuzz testing.  Going to close this issue.
