### ISSUE TITLE
using `&` I'm unable to access nested structs in a map[string]interface?

### ISSUE THREAD

**Issue by falafflepotatoe** [slongfield/pyfmt#5]
Hey good job, this looks great. 

I've been playing with the getElement function, Not sure if this is even a bug but I wanted your comments.

What I'm trying to do is access foo.bar.someStruct.someProp, usually from a slice of structs but for today from a map[string]interface{}.

I cant access anything with `& somestruct{...}`, with no ampersend its fine

    type b struct {
	Bazzer int
	Bazzle []int
    }
    
    func main() {
	a := map[string]interface{} {
		"bar"   : map[string]interface{} {
				"baz": &b{0,[]int{1,2,3}},
				"buzz": []int{1,2,3} },
		"baz"   : []int{1,2,3},
		"bazzle": []string{"1","2","3"} }

	b,err := getElement("bar.baz.Bazzle[0]",0,a)
	fmt.Println(b,err)
    }

Expected output: one of the struct members,
Actual output: attempted to get item by name in non-struct, non-map
If I drop the `&` before the struct `&b {...}` it works fine.

thoughts?

sorry if not a bug, I noticed this while I was just giving a quick evaluation of whether the software  if it will work for my purposes. Cheers it looks great.

**Comment by slongfield** [comment]
Thanks!

Yea, get_element doesn't dereference internal struct pointers, but it probably should. I'll fix this.

Thanks for trying it out!

**Comment by falafflepotatoe** [comment]
Sweet. Glad it was that simple.
